### ISSUE TITLE
cloth与rigidbody的碰撞处理

### ISSUE THREAD

**Issue by pentatracy5** [Housz/awesome-simulation#1]
hello，请问有没有讲解如何处理cloth与rigidbody的碰撞的资料或者代码推荐，我这边目前在看《Simulation of Clothing with Folds and Wrinkles》中5.1一节引用的文章，基本都是跟level set有关的，但是看不太懂。多谢了

**Comment by Housz** [comment]
您好，我对这方面也不是很了解，要不您看看这两位的工作?
https://www.cs.cmu.edu/~minchenl/
https://wanghmin.github.io/

**Comment by pentatracy5** [comment]
好的，谢谢
